const DOLMUS_SOZLERI = [
  'Onat dolmuş sürüyor, radyoyu sonuna kadar açmış.',
  'Onat dolmuşta kaza yaptı, ilk sözü "para üstü lazım mı" oldu.',
  'Onat dolmuşa binmiş, şoföre "hocam inecek var" diye bas bas bağırıyor ama daha durak gelmedi.',
  'Onat dolmuşta arka koltuğa tıkıldı, "sağ öndeyim" diye içinden geçirdi.',
  'Onat dolmuşu trafik ışığında kırmızıda geçirdi, arkadaki teyze "yavrum acelen ne" dedi.',
  'Onat dolmuşta telefonla konuşan adama "hocam sesli konuşuyosun" demeye çalışıp vazgeçti.',
  'Onat dolmuş şoförlüğüne başladığı ilk gün üç kere yanlış yola saptı.',
  'Onat dolmuşta parayı önden arkaya, arkadan öne yolcudan yolcuya geçirirken bir 20 lirayı kaybetti.',
  'Onat dolmuşta müzik değiştirmeye kalktı, tüm dolmuş "eskisi kalsın" diye bağırdı.',
  'Onat dolmuşla köprüde kaldı, yanındaki abi "bu trafik bitmez" deyince Onat direksiyonu bıraktı.',
  'Onat dolmuşa son koltuğa oturdu, her hız kesişte tavana kafasını çarptı.',
  'Onat dolmuşta kaza yaptı, sigortacıyı değil önce annesini aradı.',
  'Onat dolmuş kuyruğunda bekledi, sırası gelince "ben zaten inecektim" deyip indi.',
  'Onat dolmuşta "durak" diye bağırdı ama şoför Onat\'ın sesini duymadı, üç durak sonra indi.',
  'Onat dolmuş sürerken bir yandan simit yiyordu, direksiyon simit kırıntısıyla doldu.',
  'Onat dolmuşta oturduğu koltuğun yayı patlamıştı, tüm yolculuk boyunca eğik oturdu.',
  'Onat dolmuşa bindiğinde tam 1 lira eksik çıktı, şoförle göz göze gelmemek için pencereden dışarı baktı.',
  'Onat dolmuş sürüyor, dur durak demeden her el kaldırana duruyor.',
  'Onat dolmuşta kaza yaptı, karşı taraf indi bakmaya, Onat hâlâ emniyet kemerini çözmeye çalışıyordu.',
  'Onat dolmuşta uyuyakaldı, son durağa kadar gitti, şoför onu uyandırmaya kıyamadı.',
  'Onat dolmuş şoförüne "hızlı git" dedi, şoför "sen mi süreceksin" diye sordu.',
  'Onat dolmuşta cam kenarına oturdu, yağmur camdan içeri sızıyordu ama kimseye söylemedi.',
  'Onat dolmuşla kaza yaptı, ilk iş olarak dolmuşun plakasını ezberledi, kendi plakasını değil.',
  'Onat dolmuşta yer yoktu, şoför "sığdırırım" dedi, Onat üç kişinin arasına mengeneyle sıkıştı.',
  'Onat dolmuş sürerken telefonuna bakan bir yolcuya aynadan bakıp içini çekti.',
  'Onat dolmuşta kaza yaptı, tazminat yerine karşı tarafla dolmuş şoförlüğü sohbetine daldı.',
  'Onat dolmuşa park yeri ararken üç sokak dolaştı, sonunda dolmuş durağına park etti.',
  'Onat dolmuşta oturan yaşlı teyzeye yer verdi, kendisi ayakta tüm yolu tavana tutunarak gitti.',
  'Onat dolmuş sürüyor, her kırmızı ışıkta "bu da geçer" diye söyleniyor.',
  'Onat dolmuşta kaza yaptı ama hasar o kadar ufaktı ki iki taraf da gülüp yoluna devam etti.',
];

module.exports = { DOLMUS_SOZLERI };
